
development:
  cloud_name: di820hhex
  api_key: '317984298387436'
  api_secret: wJoCkGBuuRnRAQGTpAwcqxaNBrY
  enhance_image_tag: true
  static_image_support: false
test:
  cloud_name: di820hhex
  api_key: '317984298387436'
  api_secret: wJoCkGBuuRnRAQGTpAwcqxaNBrY
  enhance_image_tag: true
  static_image_support: false
